# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cond_t <- function(IQ, qj) {
    .Call('_samc_cond_t', PACKAGE = 'samc', IQ, qj)
}

.cond_t_iter <- function(IQ, qj) {
    .Call('_samc_cond_t_iter', PACKAGE = 'samc', IQ, qj)
}

.build_convolution_cache_float <- function(kernel, resistance, fidelity, absorption, symmetric, threads = 1L) {
    .Call('_samc_build_convolution_cache_float', PACKAGE = 'samc', kernel, resistance, fidelity, absorption, symmetric, threads)
}

.build_convolution_cache_double <- function(kernel, resistance, fidelity, absorption, symmetric, threads = 1L) {
    .Call('_samc_build_convolution_cache_double', PACKAGE = 'samc', kernel, resistance, fidelity, absorption, symmetric, threads)
}

.get_convolution_list_float <- function(ca) {
    .Call('_samc_get_convolution_list_float', PACKAGE = 'samc', ca)
}

.get_convolution_list_double <- function(ca) {
    .Call('_samc_get_convolution_list_double', PACKAGE = 'samc', ca)
}

.convolution_short_float <- function(steps, ca, pop_in, threads = 1L) {
    .Call('_samc_convolution_short_float', PACKAGE = 'samc', steps, ca, pop_in, threads)
}

.convolution_short_double <- function(steps, ca, pop_in, threads = 1L) {
    .Call('_samc_convolution_short_double', PACKAGE = 'samc', steps, ca, pop_in, threads)
}

.convolution_long_float <- function(ca, init, threads = 1L) {
    .Call('_samc_convolution_long_float', PACKAGE = 'samc', ca, init, threads)
}

.convolution_long_double <- function(ca, init, threads = 1L) {
    .Call('_samc_convolution_long_double', PACKAGE = 'samc', ca, init, threads)
}

.sum_qn_q <- function(M, M2, q, t) {
    .Call('_samc_sum_qn_q', PACKAGE = 'samc', M, M2, q, t)
}

.sum_qn_q_iter <- function(M, M2, q, t) {
    .Call('_samc_sum_qn_q_iter', PACKAGE = 'samc', M, M2, q, t)
}

.diagf_par <- function(M, threads) {
    .Call('_samc_diagf_par', PACKAGE = 'samc', M, threads)
}

.diagf_par_iter <- function(M, threads) {
    .Call('_samc_diagf_par_iter', PACKAGE = 'samc', M, threads)
}

.qpow_row <- function(M, vec, t) {
    .Call('_samc_qpow_row', PACKAGE = 'samc', M, vec, t)
}

.qpow_col <- function(M, vec, t) {
    .Call('_samc_qpow_col', PACKAGE = 'samc', M, vec, t)
}

.sum_qpowrv <- function(M, rv, t) {
    .Call('_samc_sum_qpowrv', PACKAGE = 'samc', M, rv, t)
}

.solver_cache <- function() {
    .Call('_samc_solver_cache', PACKAGE = 'samc')
}

.f1 <- function(M, SC) {
    .Call('_samc_f1', PACKAGE = 'samc', M, SC)
}

.f1_iter <- function(M) {
    .Call('_samc_f1_iter', PACKAGE = 'samc', M)
}

.sum_qpow_row <- function(M, vec, t) {
    .Call('_samc_sum_qpow_row', PACKAGE = 'samc', M, vec, t)
}

.sum_qpow_col <- function(M, vec, t) {
    .Call('_samc_sum_qpow_col', PACKAGE = 'samc', M, vec, t)
}

.f_row <- function(M, vec, SC) {
    .Call('_samc_f_row', PACKAGE = 'samc', M, vec, SC)
}

.f_row_iter <- function(M, vec) {
    .Call('_samc_f_row_iter', PACKAGE = 'samc', M, vec)
}

.f_col <- function(M, vec, SC) {
    .Call('_samc_f_col', PACKAGE = 'samc', M, vec, SC)
}

.f_col_iter <- function(M, vec) {
    .Call('_samc_f_col_iter', PACKAGE = 'samc', M, vec)
}

