# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cond_t <- function(IQ, qj) {
    .Call('_samc_cond_t', PACKAGE = 'samc', IQ, qj)
}

.cond_t_iter <- function(IQ, qj) {
    .Call('_samc_cond_t_iter', PACKAGE = 'samc', IQ, qj)
}

.build_convolution_cache <- function(kernel, resistance, fidelity, absorption, symmetric, threads = 1L) {
    .Call('_samc_build_convolution_cache', PACKAGE = 'samc', kernel, resistance, fidelity, absorption, symmetric, threads)
}

.get_convolution_list <- function(ca) {
    .Call('_samc_get_convolution_list', PACKAGE = 'samc', ca)
}

.convolution_short <- function(steps, ca, pop_in, threads = 1L) {
    .Call('_samc_convolution_short', PACKAGE = 'samc', steps, ca, pop_in, threads)
}

.convolution_long <- function(ca, pop_in, threads = 1L) {
    .Call('_samc_convolution_long', PACKAGE = 'samc', ca, pop_in, threads)
}

.sum_qn_q <- function(M, M2, q, t) {
    .Call('_samc_sum_qn_q', PACKAGE = 'samc', M, M2, q, t)
}

.sum_qn_q_iter <- function(M, M2, q, t) {
    .Call('_samc_sum_qn_q_iter', PACKAGE = 'samc', M, M2, q, t)
}

.diagf_par <- function(M, threads) {
    .Call('_samc_diagf_par', PACKAGE = 'samc', M, threads)
}

.diagf_par_iter <- function(M, threads) {
    .Call('_samc_diagf_par_iter', PACKAGE = 'samc', M, threads)
}

.psid_long <- function(M, psi, dg, SC) {
    .Call('_samc_psid_long', PACKAGE = 'samc', M, psi, dg, SC)
}

.psid_long_iter <- function(M, psi, dg) {
    .Call('_samc_psid_long_iter', PACKAGE = 'samc', M, psi, dg)
}

.qpow_row <- function(M, vec, steps) {
    .Call('_samc_qpow_row', PACKAGE = 'samc', M, vec, steps)
}

.qpow_col <- function(M, col, steps) {
    .Call('_samc_qpow_col', PACKAGE = 'samc', M, col, steps)
}

.sum_qpowrv <- function(M, rv, steps) {
    .Call('_samc_sum_qpowrv', PACKAGE = 'samc', M, rv, steps)
}

.solver_cache <- function() {
    .Call('_samc_solver_cache', PACKAGE = 'samc')
}

.f1 <- function(M, SC) {
    .Call('_samc_f1', PACKAGE = 'samc', M, SC)
}

.f1_iter <- function(M) {
    .Call('_samc_f1_iter', PACKAGE = 'samc', M)
}

.sum_qpow_row <- function(M, vec, steps) {
    .Call('_samc_sum_qpow_row', PACKAGE = 'samc', M, vec, steps)
}

.sum_qpow_col <- function(M, col, steps) {
    .Call('_samc_sum_qpow_col', PACKAGE = 'samc', M, col, steps)
}

.f_row <- function(M, vec, SC) {
    .Call('_samc_f_row', PACKAGE = 'samc', M, vec, SC)
}

.f_row_iter <- function(M, vec) {
    .Call('_samc_f_row_iter', PACKAGE = 'samc', M, vec)
}

.f_col <- function(M, col, SC) {
    .Call('_samc_f_col', PACKAGE = 'samc', M, col, SC)
}

.f_col_iter <- function(M, col) {
    .Call('_samc_f_col_iter', PACKAGE = 'samc', M, col)
}

